### ISSUE TITLE
Is there a way to apply draggable crop re-sizing

### ISSUE THREAD

**Issue by nkmekal1** [ricardo-ch/react-easy-crop#101]
We need a way to enable users to crop images via a select/drag style (a.k.a free form cropping). Currently looks like the library has a fixed crop size specification property.

This means if crop size is not provided, we can still auto compute the crop size however provide a free form (re-size) cropping ability for the user.

Here is a library that provides that free form cropping ability by default
https://github.com/DominicTobias/react-image-crop

any thoughts?

**Comment by ValentinH** [comment]
There is no way to do this with this library. If you want to have a free form crop, you should definitely use the cropper from Dominic Tobias, it's a great library.

I've actually written this component because we didn't want to let the user select the ratio of the new image on ricardo.ch. At that time, there was no good library to achieve what we wanted to do.

I prefer to be clear: we will never implement such a feature as part of this library. I prefer it to stay specific: just cover a few use cases but cover them well.

I hope you understand. 🙂
