### ISSUE TITLE
Removal of emotion

### ISSUE THREAD

**Issue by stefanoruth** [ricardo-ch/react-easy-crop#126]
Hi, would you be interested in a pr for the removal of emotions?

The main reason behind this would be got get a smaller bundlesize.

Right now its on [12.5 kb](https://bundlephobia.com/result?p=react-easy-crop@2.1.1)

And the main reason for this is emotion.

I would propose a pr for the removel of emotion, and maybe a solution with inline scroped style tags, if you are open for a pr?

**Comment by ValentinH** [comment]
Hi!

Indeed, `emotion` represents the biggest part of the library and I'm not happy with it. 😞

I decided to use CSS-in-JS because I didn't want to ask everyone to include a css file. This is a common issue with every libraries that need to set some CSS rules.

I doubt that you can support all existing styles with only plain `style` tags (because of pseudo-elements) but if you find a way, I could consider a PR.

I could also consider switching to plain css that would need to be imported.
