### ISSUE TITLE
Unable to zoom out on rotated image and aspect ratio

### ISSUE THREAD

**Issue by ajlende** [ricardo-ch/react-easy-crop#151]
Rotating an image and adjusting the aspect ratio to match the rotation makes the crop area smaller than the image and unable to be zoomed out.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5129775/86406814-08039400-bc71-11ea-84b6-0adb84ecb72e.png">

CodeSandbox for the issue: https://codesandbox.io/s/react-easy-crop-image-aspect-fyie3

Steps to reproduce the issue:

  1.  Rotate image 90 degrees
  2.  Set aspect ratio to match the rotated image

**Observed behaviour:** The crop area is smaller than the image even though zoom is set to 0.

**Expected behaviour:** The crop area is the same size as the image, as in the initial state.

**Comment by ValentinH** [comment]
Good catch indeed! I think it needs to be handled in the [computeSizes](https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L206) function (especially the `getCropSize` one). Would you like to try to fix it and submit a PR?

**Comment by ValentinH** [comment]
After starting to work on this issue, I've noticed that issue #152 is also linked to this bug. The issue is inside the [getCropSize()](https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.ts#L7) helper and I think it needs to take the container size into account to compute the crop area size.

Indeed, in your example, if you change the output window aspect, then the crop area is correctly sized:
![image](https://user-images.githubusercontent.com/2678610/87858783-b88bbc00-c930-11ea-8087-dac3e01c0147.png)

**Comment by ValentinH** [comment]
I'm re-opening in case @ajlende comes up with a PR :)

**Comment by ValentinH** [comment]
This looks fixed. Please comment to reopen.
