### ISSUE TITLE
Be able to zoom based on the 

### ISSUE THREAD

**Issue by RichardHpa** [ricardo-ch/react-easy-crop#162]
This is a feature request rather than a bug.

It would be good if you could add a property to be able to zoom out of the image based on the larger axis rather than it being limited to the smaller one. This is different than restrictPosition as I would still want it to be restricted but just on the larger axis.

In the hook example (https://codesandbox.io/s/v69ly910ql), if I could zoom out to include the whole image inside the cropper and when I crop the image it includes white/black space above or bellow the image, that would be amazing.

**Comment by ValentinH** [comment]
I can actually get close to what you need by setting a `minZoom` value lower than 1.

However, with the option you suggest to add, would it change the zoom scale (1 being the zoom value at which the whole image is inside the crop area)? If yes, this might be trickier.

Would you like to submit a PR for this? I think it should handled in the `restrictPosition` function of the helpers.

**Comment by YemreAybey** [comment]
Hello @ValentinH I didn't want to add another issue but I would like to ask a question to you. I would like to add my maxZoom property in a dynamic way so that you can't zoom in lower than 600 x 600 pixels is there any way or math to do it. Of  course I can add maxZoom in a dynamic way right now but I don't know how to set it to certain number so that the cropped image can't be lower than 600 x 600 pixels.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
