### ISSUE TITLE
croppedAreaPixels 'x' value is different on Chrome and Firefox

### ISSUE THREAD

**Issue by mylesdawson** [ricardo-ch/react-easy-crop#234]
**Describe the bug**
- Rotate image 90 degrees
- Log croppedAreaPixels
- Observer the x field is different when logged inside Chrome (89.0) than Firefox (87.0)

**To Reproduce**
- Visit Sandbox: [image-upload-demo-forked](https://codesandbox.io/s/react-easy-crop-custom-image-demo-forked-dclqs?file=/src/index.js)
- Upload some image
- Observer the console (filtered by info)
- Compare the console x values between Firefox and Chrome

**Expected behavior**
croppedAreaPixel's x field value should be the same between Firefox and Chrome

**Comment by ValentinH** [comment]
When rotating and cropping the image, a lot of mathematic operations and rounding are applied. I guess that depending on some specific operation implementations, we can have different results because of rounding down or up.

Do you only observe a difference between these 2 browsers or did you check other browsers?

**Comment by mylesdawson** [comment]
Hey thanks for the reply.

I have only observed the difference between Chrome and Firefox. Edge appears the same as Chrome and I have yet to test Safari. I'll look into the rotating and cropping image code to see if I can uncover anything that could have produced this bug

**Comment by mylesdawson** [comment]
Closing this issue for now. Couldn't find the culprit that was causing differences between browsers
