### ISSUE TITLE
Setting aspect ratio to 1 returns different height & width for croppedAreaPixels

### ISSUE THREAD

**Issue by raRaRa** [ricardo-ch/react-easy-crop#27]
## Are you reporting a bug?

- Demo that shows the issue. I console log the `croppedAreaPixels` in `onCropComplete`
[Demo](https://codesandbox.io/s/1v6wm2jz34).

- Provide the steps to reproduce the issue, e.g.:

  1.  Set aspect ratio to 1.
  2.  Add image
  3. Note how the `croppedAreaPixels` in `onCropComplete` have different width and height.

  **Observed behaviour:** The width and height in `croppedAreaPixels` are different.

  **Expected behaviour:** The width and height in `croppedAreaPixels` should be the same.

**Comment by ValentinH** [comment]
Hey @raRaRa, thanks for reporting this issue. This has already bothered me in the past and this was mostly due to floating approximation errors when converting from percentage values to pixel ones.

I have know prepared a fix that will always ensure the width is tied to height and aspect. Also what do you think about rounding the pixels so they  are always integers?

**Comment by ValentinH** [comment]
Please see #28 and let me know if it fixes your issue? 🙂

**Comment by raRaRa** [comment]
Hey @ValentinH, thanks for the quick response to this issue. That sounds good to me, since I'm already converting these values to integers on my end. I'll give it a try! Thanks again!

**Comment by raRaRa** [comment]
I can confirm that `1.9.0-alpha.0` fixes the problem. Thanks!

**Comment by ValentinH** [comment]
Just released v1.9.0. 🎉
