### ISSUE TITLE
Cropped image size is bigger than original

### ISSUE THREAD

**Issue by itmaxxx** [ricardo-ch/react-easy-crop#288]
**Describe the bug**
Cropped image size is bigger than the original image, even if we crop it.

**To Reproduce**
1. Go to https://codesandbox.io/s/q8q1mnr01w?file=/src/index.js
(Original image size is ~172kb)
![original](https://user-images.githubusercontent.com/38819868/131707925-c92f07a7-5b2a-497b-b235-8e62b9ae06f3.jpeg)
2. Click "Show result"
3. Download the result image and see that its size is ~184kb
![cropped](https://user-images.githubusercontent.com/38819868/131707983-390f23ee-a1d9-456f-95a3-8a9a24a2e9ba.jpg)

The same error occurs in my project, but the difference in the size of the original and croped is 10x more.

**Expected behavior**
Cropped image size should be smaller than the original image.

**Comment by ValentinH** [comment]
The canvas cropping logic is not part of the library and is just provided as an example. I guess you can tweak the quality parameter of the canvas base 64 export to make the output lighter.

**Comment by ValentinH** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by itmaxxx** [comment]
Thank you!!!

**Comment by suryateja77By** [comment]
Hi, @itmaxxx I am experiencing the same problem as yours, my 4MB image turns out to be 22MB after cropping. As suggested by @ValentinH I have added a quality parameter to the base64 export but did not see any change.
Spent a few hours on this but not sure where am doing it wrong.

Could you share the solution you have applied to your project? Thanks in advance.

Here is the change I made to the canvasUtis file as given in the example [https://codesandbox.io/s/q8q1mnr01w?file=/src/cropImage.js](https://codesandbox.io/s/q8q1mnr01w?file=/src/cropImage.js)
`return new Promise((resolve) => {
    canvas.toBlob(
      (file) => {
        resolve(URL.createObjectURL(file));
      },
      'image/jpg',
      0.8
    );
  });`

**Comment by h27-webdev** [comment]
@suryateja77By Hi, I am experiencing the same issue. Even after applying a quality filter, the image is still bloated. Did you find any workaround for this?

**Comment by suryateja77By** [comment]
> @suryateja77By Hi, I am experiencing the same issue. Even after applying a quality filter, the image is still bloated. Did you find any workaround for this?

Hi, I do not remember finding any workaround, I have used another lib/technique to reduce the size of the image.
