### ISSUE TITLE
Editing an already cropped image

### ISSUE THREAD

**Issue by henryoliver** [ricardo-ch/react-easy-crop#36]
Love the library, thanks for this helpful tool!

How can I set the **crop x,y** based on an already saved **croppedAreaPixels**?

Context:
We are getting the croppedAreaPixels coordinates and want to give the user the ability to continue editing an already cropped image. How can we set state **crop x,y** based on the **croppedAreaPixels**?

Thanks!

**Comment by ValentinH** [comment]
😬 I've thought about this use-case before and knew it was coming! 😄 

This is currently quite tricky but definitely needed.

One way to do it would be to expose the opposite function of `computeCroppedArea` (https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.js#L54). 
I need to think more about it 🤔

**Comment by henryoliver** [comment]
Thanks for the response @ValentinH, I will try to revert the function to get the crop X and Y. 

Thanks for your help, that is a big deal for us so if it worked we may move forward with this library.

Henry

**Comment by ValentinH** [comment]
I think the easiest way would be for you to also store the crop{x ,y} and zoom values when saving.


If this is not an option, you indeed need to reverse the function. You can submit a PR if you want and I can help implementing it if needed. 🙂

**Comment by ValentinH** [comment]
I've actually thought about it while driving and I have a better idea about how to implement this.

First, the library should enable to set the initial cropped area (like in your case) without having the developer to compute it up-front. Indeed, computing it requires knowing the original image size and since the library is loading the image, it has everything to computer it.

Thus, I would introduce a new `initialCroppedAreaPixels` prop that would be used when the component mount to set the crop and zoom value automatically. Computing the crop and zoom would be done inside a `getInitialCropAndZoom()` helper that could also be exported if some developers want to use it directly (if the image size has changed in between for example).

Would you like to implement it or should I do it? (I'm fine doing it but if you are happy to contribute to this project, you have the priority 🎉).

**Comment by henryoliver** [comment]
Appreciate the idea, but If you just send me the formula, I could implement it on my side right the way. I'm doing several attempts here without success. Here is one of my attempts:

```
crop_width = (bottom_right_x - top_left_x ) * width
crop_height = (bottom_right_y - top_left_y) * height
crop_x = width * top_left_x * zoom - (width * zoom) / 2 + crop_width / zoom
crop_y = height * top_left_y * zoom - (height * zoom) / 2 + crop_height / zoom
```

**Comment by ValentinH** [comment]
I had a hard time to find the right formula (I'm too lazy to do proper math ^^) but managed to found it! 🎉 

I've published an alpha version for you to try out: 1.12.0-alpha.0.

Here's a demo of it: https://codesandbox.io/s/pmj19vp2yx

**Comment by henryoliver** [comment]
Thanks @ValentinH! It worked perfectly! 

Follow how I set the initial crop:

```
setCropData() {
    const { productImageNode } = this.props;
    const { width: naturalWidth, height: naturalHeight } = productImageNode.photo;
    const { top_left_x, top_left_y, bottom_right_x, bottom_right_y } = productImageNode.crop;

    const currentWidth = Math.round((bottom_right_x - top_left_x) * naturalWidth);
    const currentHeight = Math.round((bottom_right_y - top_left_y) * naturalHeight);
    const aspect = Math.round((currentWidth / currentHeight) * 1000) / 1000;

    const currentRatioWidth = naturalWidth / currentWidth;
    const currentRatioHeight = naturalHeight / currentHeight;
    const zoomFromWidth = Number((Math.ceil(currentRatioWidth * 20 - 0.5) / 20).toFixed(2));
    const zoomFromHeight = Number((Math.ceil(currentRatioHeight * 20 - 1) / 20).toFixed(2));
    const zoom = (aspect < 1) ? zoomFromHeight : zoomFromWidth;

    const initialCroppedAreaPixels = { width: currentWidth, height: currentHeight, x: Math.round(top_left_x * naturalWidth), y: Math.round(top_left_y * naturalHeight) }

    this.setState({
      zoom,
      aspect,
      initialCroppedSet: true,
      initialCroppedAreaPixels
    });
  }

onCropComplete = (croppedArea, croppedAreaPixels) => {
    clearTimeout(this.state.gridTimer);
    this.gridTimer = setTimeout(() => this.setState({ showGrid: false }), 750);

    this.setState({
      croppedArea,
      croppedAreaPixels,
      aspect: this.props.productImageNode.aspect
    }, () => {
      if (this.props.productImageNode.crop && !this.state.initialCroppedSet) {
        this.setCropData();
      }
    });
  };
```

**Comment by ValentinH** [comment]
I'm not sure to understand why you need to do so much computations, I didn't meant to require this when implementing this parameters.

In order to understand, could you share example data of what contains your `productImageNode`?

Also, be careful, the published version is still alpha and the API might change when I publish the stable version: I still have to see if current API is what make the most of sense for developers.

**Comment by ValentinH** [comment]
Hey @henryoliver , I've updated the demo (https://codesandbox.io/s/pmj19vp2yx)  to show how to synchronize the latest crop to the local storage and read it on mount. Let me know if it helps?

Also please note that I had to unpublish the `react-easy-crop@1.12.0-alpha.0` version because it wasn't really an alpha. I've published `react-easy-crop@1.12.0-alpha.1` instead.

**Comment by henryoliver** [comment]
Thanks, @ValentinH! Just updated it, appreciate your work on helping us, man. That new implementation will go to production soon next week, so far that fulfilled our need here.

**Comment by ValentinH** [comment]
Stable 1.12.0 was just released 🎉
