### ISSUE TITLE
Improve edge detection when rotation is used

### ISSUE THREAD

**Issue by ValentinH** [ricardo-ch/react-easy-crop#52]
The current `restrictPosition()` function ([here](https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.js#L28)) does not take care of the `rotation` prop and is too restrictive.

We need to handle the rotation properly to have correct edge detections.

**Comment by MattyBalaam** [comment]
Not PR ready, but I had a play around this. It may or not be useful. I have the crop-area successfully tracking-around the area an image has roatated in. I’m _guessing_ that instead of cropping like this, the ideal would be to crop without showing any areas outside on angles outside of 0/90/180/270

https://github.com/MattyBalaam/react-easy-crop/commit/f2bdb2d1c39e22ab5090182f1540847d5b992358

**Comment by ValentinH** [comment]
Thanks for this, I'll check it later today 🙂

**Comment by ValentinH** [comment]
I just checked it and I'm actually not sure to understand why you are modifying the crop area size based on the rotation. This behaviour does not feel really familiar to me. 🤔 

I would expect to keep the crop area fixed but only adapt the rules of the edge detection.

Anyway, thanks for giving this a try! 👍

**Comment by MattyBalaam** [comment]
I wasn't sure where to start as I'm not totally sure how everything works conceptually behind the scenes, so just tried at the first place I found I could manipulate things. I'll take a look at the edge detection tomorrow.

**Comment by MattyBalaam** [comment]
I adapted the code to be in the restrict function based on the rule of keeping at least part of the image without the crop area.

https://github.com/MattyBalaam/react-easy-crop/commit/0e665daa017a45628069f7994f684c2917a7aeb1

A caveat with this is that when the demo portrait image is rotated 90 degrees then it is possible to manipulate the zoom so that the width of the image becomes smaller than the crop. Do you have pointers about the best place to adjust the zoom settings in this situation?

![Screen Shot 2019-08-22 at 17 10 52](https://user-images.githubusercontent.com/1246923/63531162-d4f45e00-c4ff-11e9-9ba6-0da9d00faf68.png)

I also spent quite a while attempting to figure out way to restrict based on keeping the crop entirely within the image, but I’ve not been able to quite work out how to convert the co-ordimates properly. I might take another look, but it has been quite a slog trying to work it out.

**Comment by MattyBalaam** [comment]
This modification keeps the crop within the image - however the crop itself changes size when the rotation is changed.

```
export function getCropSize(imgWidth, imgHeight, aspect, rotation) {
  if (imgWidth >= imgHeight * aspect) {
    return translateSize(imgHeight * aspect, imgHeight, rotation)
  }

  return translateSize(imgWidth, imgWidth / aspect, rotation)
}
```

**Comment by ValentinH** [comment]
WOW thank you so much, this looks awesome!! Could you already submit a PR for better visibility so that we can iterate there? 🙂 

Automatically setting the zoom higher when needed should not be an issue 🙂

**Comment by ValentinH** [comment]
This is done in v1.15 🎉
